// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spsbvpnsgtdqqeetzdsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwc2J2cG5zZ3RkcXFlZXR6ZHNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMTY3NjQsImV4cCI6MjA2NDg5Mjc2NH0.V4O2MeMqy5IEGiv5R-XdrqggW3gblI2rP4XTJiUWPIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);